name: magic_buffer
description: Buffer class JS implementation based on the buffer module from [node.js].The goal is to provide an API that is 100% identical to [node's Buffer API].
version: 0.0.16
repository: https://github.com/pheonixeye/magic_buffer.git

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  ieee754_dart: ^0.0.11

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
